# Generated by Django 6.1.1 on 2026-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text='Dernière ouverture du panneau de notifications (badge).', null=True, verbose_name='notifications consultées le'),
        ),
    ]
