# Generated by Django 6.1.1 on 2026-09-23 01:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='raison sociale')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='logo')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('ice', models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise", max_length=40, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, help_text='Registre du Commerce', max_length=40, verbose_name='RC')),
                ('patente', models.CharField(blank=True, max_length=40, verbose_name='patente')),
                ('if_number', models.CharField(blank=True, help_text='Identifiant Fiscal', max_length=40, verbose_name='IF')),
                ('bank_details', models.TextField(blank=True, verbose_name='coordonnées bancaires')),
                ('default_vat', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='TVA par défaut (%)')),
                ('invoice_footer', models.TextField(blank=True, verbose_name='pied de facture')),
                ('invoice_footer_fr', models.TextField(blank=True, null=True, verbose_name='pied de facture')),
                ('invoice_footer_ar', models.TextField(blank=True, null=True, verbose_name='pied de facture')),
                ('invoice_footer_en', models.TextField(blank=True, null=True, verbose_name='pied de facture')),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=5, verbose_name='langue par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': "paramètres de l'entreprise",
                'verbose_name_plural': "paramètres de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('description_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('description_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=16, verbose_name='type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valeur')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valide du')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valide au')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('PRINT', 'Impression')], max_length=16, verbose_name='action')),
                ('model_name', models.CharField(max_length=64, verbose_name='modèle')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='représentation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(blank=True, help_text='Null pour les actions système.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx')],
            },
        ),
    ]
