# Generated by Django 6.1.1 on 2026-09-23 01:45

import apps.vehicles.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('economy', 'Économique'), ('compact', 'Compacte'), ('family', 'Familiale'), ('suv', 'SUV / 4x4'), ('electric', 'Électrique / Hybride'), ('luxury', 'Luxe'), ('minibus', 'Minibus')], max_length=20, unique=True, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'catégorie de véhicule',
                'verbose_name_plural': 'catégories de véhicules',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('brand', models.CharField(max_length=100, verbose_name='marque')),
                ('model', models.CharField(max_length=100, verbose_name='modèle')),
                ('plate_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='immatriculation')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix / jour')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='photo principale')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], db_index=True, default='available', max_length=20, verbose_name='état')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Essence'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='diesel', max_length=16, verbose_name='carburant')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='manual', max_length=16, verbose_name='boîte')),
                ('seats', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='places')),
                ('year', models.PositiveSmallIntegerField(validators=[apps.vehicles.models.validate_year], verbose_name='année')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='kilométrage')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='vehicles.carcategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ('brand', 'model', 'plate_number'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='image')),
                ('is_main', models.BooleanField(default=False, verbose_name='image principale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.car', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'photo de véhicule',
                'verbose_name_plural': 'photos de véhicules',
                'ordering': ('-is_main', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('description', models.TextField(verbose_name='description')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='coût')),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilométrage au service')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='prochain service')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.car', verbose_name='véhicule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'maintenance',
                'verbose_name_plural': 'maintenances',
                'ordering': ('-date',),
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'category'], name='vehicles_ca_status_ab2226_idx'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_day__gte', 0)), name='car_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('car',), name='unique_main_image_per_car'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['car', '-date'], name='vehicles_ma_car_id_4dd643_idx'),
        ),
    ]
