# Generated by Django 6.1.1 on 2026-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carimage',
            name='unique_main_image_per_car',
        ),
        migrations.AlterField(
            model_name='carimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='image principale'),
        ),
    ]
