# Generated by Django 6.1.1 on 2026-09-23 01:45

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='année')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='dernier numéro')),
            ],
            options={
                'verbose_name': 'compteur de factures',
                'verbose_name_plural': 'compteurs de factures',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='numéro')),
                ('sequence_year', models.PositiveIntegerField(db_index=True, default=0, verbose_name='année de séquence')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='émise le')),
                ('client_snapshot', models.JSONField(blank=True, default=dict, verbose_name='client (instantané)')),
                ('car_snapshot', models.JSONField(blank=True, default=dict, verbose_name='véhicule (instantané)')),
                ('dates_snapshot', models.JSONField(blank=True, default=dict, verbose_name='dates (instantané)')),
                ('price_snapshot', models.JSONField(blank=True, default=dict, verbose_name='prix (instantané)')),
                ('options_snapshot', models.JSONField(blank=True, default=list, verbose_name='options (instantané)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='sous-total')),
                ('promotion_code', models.CharField(blank=True, max_length=32, verbose_name='code promotion')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='remise')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='TVA (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='net à payer')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='fichier PDF')),
                ('printed_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'impressions")),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking', verbose_name='réservation')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='émise par')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ('-issued_at',),
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['sequence_year', '-issued_at'], name='invoicing_i_sequenc_535622_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
