# Generated by Django 6.1.1 on 2026-09-23 01:45

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nom complet')),
                ('telephone', models.CharField(db_index=True, max_length=40, verbose_name='téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('country', models.CharField(db_index=True, default='Maroc', max_length=80, verbose_name='pays')),
                ('id_document', models.CharField(blank=True, help_text='CIN pour les clients marocains, passeport sinon.', max_length=40, verbose_name='CIN / Passeport')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name',),
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['country', 'name'], name='clients_cli_country_b89182_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
