# Generated by Django 6.1.1 on 2026-09-23 01:45

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('start_date', models.DateField(db_index=True, verbose_name='date de départ')),
                ('end_date', models.DateField(db_index=True, verbose_name='date de retour')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=16, verbose_name='statut')),
                ('pickup_location', models.CharField(blank=True, max_length=150, verbose_name='lieu de prise en charge')),
                ('return_location', models.CharField(blank=True, max_length=150, verbose_name='lieu de restitution')),
                ('fuel_policy', models.CharField(choices=[('full_to_full', 'Plein / Plein'), ('full_to_empty', 'Plein / Vide'), ('same_to_same', 'Même niveau')], default='full_to_full', max_length=16, verbose_name='politique carburant')),
                ('mileage_policy', models.CharField(choices=[('unlimited', 'Kilométrage illimité'), ('limited', 'Kilométrage limité')], default='unlimited', max_length=16, verbose_name='politique kilométrage')),
                ('mileage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de kilométrage (km)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.car', verbose_name='véhicule')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('user', models.ForeignKey(help_text='Employé ayant enregistré la réservation.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ('-start_date', '-id'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('option_type', models.CharField(choices=[('gps', 'GPS'), ('child_seat', 'Siège enfant'), ('additional_driver', 'Conducteur additionnel'), ('insurance_full', 'Assurance tous risques'), ('insurance_partial', 'Assurance partielle'), ('delivery', 'Livraison / reprise'), ('other', 'Autre')], max_length=24, verbose_name='option')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix unitaire')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bookings.booking', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'option de réservation',
                'verbose_name_plural': 'options de réservation',
                'ordering': ('option_type',),
            },
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reason', models.TextField(verbose_name='motif')),
                ('proposed_changes', models.JSONField(blank=True, default=dict, help_text='Instantané des champs à modifier : {champ: nouvelle valeur}.', verbose_name='modifications proposées')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=16, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('review_comment', models.TextField(blank=True, verbose_name='commentaire de traitement')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='bookings.booking', verbose_name='réservation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'demande de modification',
                'verbose_name_plural': 'demandes de modification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['car', 'start_date', 'end_date'], name='bookings_bo_car_id_a83c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-start_date'], name='bookings_bo_status_abd7b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='editrequest',
            index=models.Index(fields=['status', '-created_at'], name='bookings_ed_status_24f76c_idx'),
        ),
    ]
