"""Extract every translatable string from the project.

Why this exists: Django's ``makemessages`` shells out to GNU gettext
(``xgettext``), which is not installed on this machine. This script reproduces
the part we actually need — collecting the msgids — using Python's own parser
for ``.py`` files (which correctly folds implicitly-concatenated literals) and
a small scanner for the Django template tags we use.

Usage::

    python tools/extract_messages.py            # print a summary
    python tools/extract_messages.py --json out.json
    python tools/extract_messages.py --po locale/ar/LC_MESSAGES/django.po
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
APPS_DIR = PROJECT_ROOT / "apps"
TEMPLATES_DIR = PROJECT_ROOT / "templates"

#: Functions whose first positional argument is a translatable string.
TRANSLATION_CALLS = {"_", "gettext", "gettext_lazy", "gettext_noop", "ugettext_lazy"}

TRANS_TAG = re.compile(r"""\{%\s*trans\s+(?P<q>["'])(?P<text>.+?)(?P=q)""", re.S)
BLOCKTRANS_TAG = re.compile(
    r"""\{%\s*blocktrans(?P<args>[^%]*?)%\}(?P<body>.*?)\{%\s*endblocktrans\s*%\}""", re.S
)


def normalise(text: str) -> str:
    """Collapse whitespace the way Django does for template strings."""
    return " ".join(text.split()).strip()


def extract_from_python(path: Path) -> set[str]:
    """Return every literal passed to a translation function in ``path``."""
    found: set[str] = set()
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError as exc:  # pragma: no cover - a broken source file
        print(f"  ! skipping {path}: {exc}", file=sys.stderr)
        return found

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not node.args:
            continue
        func = node.func
        name = getattr(func, "id", None) or getattr(func, "attr", None)
        if name not in TRANSLATION_CALLS:
            continue

        # ``_(...)`` is often wrapped in ``% {...}`` — unwrap to the literal.
        argument = node.args[0]
        if isinstance(argument, ast.BinOp) and isinstance(argument.op, ast.Mod):
            argument = argument.left

        if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
            found.add(argument.value)
    return found


def extract_from_template(path: Path) -> set[str]:
    """Return every ``{% trans %}`` / ``{% blocktrans %}`` string in ``path``."""
    source = path.read_text(encoding="utf-8")
    found: set[str] = set()

    for match in TRANS_TAG.finditer(source):
        found.add(match.group("text"))

    for match in BLOCKTRANS_TAG.finditer(source):
        body = match.group("body")
        # Drop nested template tags and Django comments.
        body = re.sub(r"\{%.*?%\}", "", body, flags=re.S)
        body = re.sub(r"\{#.*?#\}", "", body, flags=re.S)
        if text := normalise(body):
            found.add(text)

    return found


def collect() -> dict[str, list[str]]:
    """Map every msgid to the files that use it."""
    references: dict[str, list[str]] = {}

    def record(msgid: str, origin: str) -> None:
        references.setdefault(msgid, []).append(origin)

    for path in sorted(APPS_DIR.rglob("*.py")):
        if "/migrations/" in path.as_posix() or "test" in path.name:
            continue
        for msgid in extract_from_python(path):
            record(msgid, path.relative_to(PROJECT_ROOT).as_posix())

    for path in sorted(TEMPLATES_DIR.rglob("*.html")):
        for msgid in extract_from_template(path):
            record(msgid, path.relative_to(PROJECT_ROOT).as_posix())

    return references


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", help="write the inventory as JSON")
    parser.add_argument("--po", help="write a template .po file (empty msgstr)")
    args = parser.parse_args()

    references = collect()
    msgids = sorted(references)

    print(f"{len(msgids)} unique translatable strings")

    if args.json:
        Path(args.json).write_text(
            json.dumps(references, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"JSON written to {args.json}")

    if args.po:
        lines = [
            "# Generated by tools/extract_messages.py — do not edit by hand.",
            'msgid ""',
            'msgstr ""',
            '"Content-Type: text/plain; charset=UTF-8\\n"',
            "",
        ]
        for msgid in msgids:
            escaped = msgid.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'msgid "{escaped}"')
            lines.append('msgstr ""')
            lines.append("")
        Path(args.po).parent.mkdir(parents=True, exist_ok=True)
        Path(args.po).write_text("\n".join(lines), encoding="utf-8")
        print(f"PO template written to {args.po}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
